# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'WiproTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AlamofireObjectMapper'
pod 'SVProgressHUD'
  pod 'Alamofire', '4.4.0'

   

end
